language: node_js
node_js:
- '0.12'
before_script:
deploy:
  on:
    repo: codehangar/flvote
    branch: master
  provider: heroku
  app: flvote
  api_key:
    secure: X/fneB3jTD3S6HgJwfvSb05wxKE/u/jC5O/xBlXOkOztKRg/dNzw5Xns6N6qDDWTlCEeQk4zegPto/KU15sucdA5VRnLZWM2E6CAxC41xe9ru5k5MpvQqIHXbtBwHEpWEc+QhPt3Ha9z2pnfEI3b5ZlU2BM6zFE2GYX3adQv8eiKy5tkeSs3g+o54iLUmv1SVIRuNNokajvpjJ+GQaYIdw0KQUsXo+m8yUejA1a4orFdRvcml5wv3w7Wce/AJ4ejgFzWX1d4qyG54mYo8JfJmiFgpuA0ngzUtrqsMrycNH+ZKjpC96TN6Mgc+h8sWes4wd9OrEBv41Pi1TzmX5gYuf2ra/ZFqIrTaUlq50WLmTK2E6JiqpyTz6q3cacPSx7uOUwZ74uYierSwFthVa+u7Xo4lwnnTmYE5db/UTUhPJssYWFFKB/YY9ggS1B5hUX6Hz6P5fhhFe55UsxRWqoL4vfvIsH0QcvhoPVT7Ge76htd9s6gjBOp7/sXsC0445h+nYqP+o6QtGuVeSbPOY5Vy+EI1ultJBUCMr5CqgazzKX04jRg0ihWnZcj4qFDEtrB2NirBehNvWIanLnos1YwuCeloSFljueVxOdCjngrXr4B/y0e4HDAY5pd9x6/ZUapqOp5UtU9BvLtdcLQOKEsSX+x0bGPQhCISgNDRiXiDYk=
